import React from 'react';
import { Stack, Heading, Divider, Text } from '@chakra-ui/react';

const About = () => {
  return (
    <Stack py={{ base: '30px', md: '50px' }} spacing="6">
      <Heading as="h2" fontSize="2xl">
        About Model
      </Heading>
      <Divider borderColor="gray.400" />
      <Text fontSize="lg">
        Zephyr is a series of language models that are trained to act as helpful assistants. Zephyr-7B-Beta is the first
        model in the series, and is a fine-tuned version of mistralai/Mistral-7B-v0.1 that was trained on a mix of publicly
        available, synthetic datasets using Direct Preference Optimization (DPO).
      </Text>
      <Text fontSize="lg">
        The model was initially fine-tuned on a variant of the UltraChat dataset, which contains a diverse range of synthetic
        dialogues generated by ChatGPT. We then further aligned the model with HuggingFace TRL's DPOTrainer on the
        openbmb/UltraFeedback dataset, which contain 64k prompts and model completions that are ranked by GPT-4. As a result,
        the model can be used for chat and you can check out our demo to test its capabilities.
      </Text>
      <Heading fontSize="xl">Model description</Heading>
      <Text fontSize="lg">
        Model type: A 7B parameter GPT-like model fine-tuned on a mix of publicly available, synthetic datasets.
      </Text>
      <Text fontSize="lg">Language(s) (NLP): Primarily English</Text>
      <Text fontSize="lg">License: MIT</Text>
      <Text fontSize="lg">Finetuned from model: mistralai/Mistral-7B-v0.1</Text>
      <Text fontSize="lg">Reference: HuggingFaceH4/zephyr-7b-beta</Text>
    </Stack>
  );
};

export default About;
